apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ffc-demo-ingress
  
  description: ffc-demo-ingress
  
  annotations:
    github.com/project-slug: defra/ffc-demo-ingress
    backstage.io/techdocs-ref: dir:.
  links:
    - url: https://github.com/defra/ffc-demo-ingress
      title: GitHub Repository
      icon: github

spec:
  type: Other
  lifecycle: alpha
  owner: "group:default/fcp-demo"
  