pr:
  branches:
    include:
      - main

trigger:
  batch: true
  branches:
    include:
      - "*"

resources:
  repositories:
    - repository: DEFRA-ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      #ref: refs/heads/main 
      ref: sm/341882/HelmOnlyPipeline

extends:
  template: /pipelines/common-helm-acr-publish.yaml@DEFRA-ADPPipelineCommon
  parameters:
    helmName: "sfd-helm-ingress"