parameters:
  - name: deployFromFeature
    displayName: "Deploy from Feature Branch"
    type: boolean
    default: false
  - name: deployConfigOnly
    displayName: "Deploy App Config"
    type: boolean
    default: false

pr:
  branches:
    include:
      - main
  drafts: false

trigger:
  batch: true
  branches:
    include:
      - "*"

resources:
  repositories:
    - repository: DEFRA-ADPPipelineCommon
      name: DEFRA/adp-pipeline-common
      endpoint: DEFRA
      type: github
      ref: sm/341882/HelmOnlyPipeline

extends:
  template: /pipelines/common-helm-acr-publish.yaml@DEFRA-ADPPipelineCommon
  parameters:
    programmeName: "ffc"
    serviceName: "ffc-demo-ingress"
    deployFromFeature: ${{ parameters.deployFromFeature }}
    deployConfigOnly: ${{ parameters.deployConfigOnly }}
    appBuildConfig:
      appFrameworkType: "helm"  
      projectPath: "ffc-demo-ingress/chart.yaml"
      imageRepoName: "ffc-demo-ingress"
  